Repository linode/cluster-api-provider-linode, pull requests merged in 2024-11, with the labels that each got.

#559 [feat] Add CIDR transformation for single IP addresses in firewall rules
  controller/linodefirewall_controller_helpers.go
  controller/linodefirewall_controller_helpers_test.go
  e2e/linodecluster-controller/firewall-integration/create-firewall.yaml
Labels: new-feature

#562 [fix] respect vlan interface if defined in linodemachine
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
Labels: bugfix

#564 [fix] don't immediately requeue if the error can't be fixed with a retry
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
Labels: bugfix

#563 [fix] handle case where instance already exists
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
Labels: bugfix

#531 [improvement] Add env var toggle for gzip compression of cloud-init user data
  cmd/main.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_helpers_test.go
  controller/linodemachine_controller_test.go
Labels: improvement

#573 [fix] : avoid resetting condition with severity error to severity warning
  internal/controller/linodecluster_controller_test.go
  internal/controller/linodefirewall_controller_test.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodevpc_controller_test.go
  util/reconciler/conditions.go
Labels: bugfix

#577 [deps] : update ccm version for node internal ip fix
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: dependencies

#576 [improvement] : use fixed retryAfter instead of exponential backoff
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_test.go
Labels: improvement
