Repository linode/cluster-api-provider-linode, pull requests merged in 2024-10, with the labels that each got.

#522 [improvement] : add new phase to check if we can use cloudinit or not to reduce API calls
  api/v1alpha1/conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodemachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_helpers_test.go
  controller/linodemachine_controller_test.go
Labels: improvement

#520 [improvement] adding verified clients for validation webhooks
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/linodecluster_webhook_test.go
  api/v1alpha2/linodemachine_webhook.go
  api/v1alpha2/linodemachine_webhook_test.go
  api/v1alpha2/linodeplacementgroup_webhook.go
  api/v1alpha2/linodeplacementgroup_webhook_test.go
  api/v1alpha2/linodevpc_webhook.go
  api/v1alpha2/linodevpc_webhook_test.go
  api/v1alpha2/webhook_helpers.go
Labels: improvement

#532 [fix] fix quoting of port in linodeFirewall
  templates/flavors/k3s/dns-loadbalancing/kustomization.yaml
  templates/flavors/kubeadm/dns-loadbalancing/kustomization.yaml
  templates/flavors/rke2/dns-loadbalancing/kustomization.yaml
  templates/infra/linodeFirewall.yaml
Labels: bugfix

#525 [feat] VLAN support for CAPL clusters
  api/v1alpha1/conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/linodecluster_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller_helpers.go
  templates/addons/ccm-linode/ccm-linode.yaml
  templates/flavors/rke2/vlan/kustomization.yaml
  util/vlanips.go
  util/vlanips_test.go
Labels: new-feature

#537 [fix] - add check for stackscript size limit when falling back to stackscripts, only check metadata for cloud-init size limit when actually using cloud-init to bootstrap
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_helpers_test.go
Labels: bugfix

#534 [improvement] : retry on ratelimit-reset than always waiting for 15 secs
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  util/ratelimits.go
  util/ratelimits_test.go
Labels: improvement

#538 [fix] update stackscript size check for entire stackscript data instead of just userdata
  controller/linodemachine_controller_helpers.go
Labels: bugfix

#535 [improvement] : add conditions to check if linodevpc and linodefirewall are ready
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_test.go
Labels: improvement

#540 [improvement] : simplify rate limits as we now have only one limit for POST calls
  controller/linodemachine_controller_helpers.go
  util/ratelimits.go
  util/ratelimits_test.go
  util/reconciler/defaults.go
Labels: improvement

#544 [fix] make VLAN IPs unique across controller pod restarts
  controller/linodemachine_controller_helpers.go
  util/vlanips.go
  util/vlanips_test.go
Labels: bugfix

#546 [CI] add support for custom linode environments
  .tilt/ctlptl-config.yaml
  Makefile
  Tiltfile
  devbox.json
  devbox.lock
  docs/src/developers/development.md
Labels: repo-ci-improvement

#547 [fix] Use retryAfter() instead of static 10 sec delay for optimized POST call timing
  controller/linodemachine_controller_helpers.go
Labels: bugfix

#549 [fix] : pin kubebuilder to v4.2.0 and fix controller-gen
  devbox.json
  devbox.lock
Labels: bugfix

#548 [improvement] : store subnet id in linodeVPC and remove GetVPC call
  api/v1alpha1/conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodevpc_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  controller/linodevpc_controller_helpers.go
Labels: improvement

#550 [CI] Update metadata.yaml for 0.7.0 release
  metadata.yaml
Labels: repo-ci-improvement

#551 [improvement] : simplify addr calculation and fetch instance config only for vlans
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
Labels: improvement

#552 [improvement] remove gob to save memory
  .golangci.yml
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_helpers_test.go
  controller/linodemachine_controller_test.go
  controller/linodeplacementgroup_controller_helpers.go
  controller/linodevpc_controller_helpers.go
  controller/linodevpc_controller_helpers_test.go
Labels: improvement

#553 [feat] adding vpcref to linodemachine
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  e2e/linodemachine-controller/linodecluster-vpcref-integration/assert-capi-resources.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/assert-linodemachine.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/assert-vpc.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/check-vpc-lm-deletion.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/create-cluster-vpc.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/create-linodemachine.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/assert-capi-resources.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/assert-linodemachine.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/assert-vpc.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/check-vpc-lm-deletion.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/create-cluster-vpc.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/create-linodemachine.yaml
Labels: new-feature

#557 [deps] Kubernetes dep upgrades and go version upgrade
  Dockerfile
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeplacementgroups.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  config/rbac/role.yaml
  devbox.json
  devbox.lock
  e2e/linodecluster-controller/firewall-integration/chainsaw-test.yaml
  go.mod
  go.sum
  hack/templates/opentelemetry.go.gotpl
  observability/wrappers/interfaces.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  observability/wrappers/runtimeclient/runtimeclient.gen.go
  observability/wrappers/runtimereconciler/runtimereconciler.gen.go
Labels: dependencies

#556 [feat] Remove kube-rbac-proxy to expose metrics and replace it with current best practice
  Tiltfile
  cmd/main.go
  cmd/main_test.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/allow-webhook-traffic.yaml
  config/network-policy/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  go.mod
  go.sum
Labels: new-feature

#558 [fix] disable LDE for flatcar
  .github/filters.yml
  e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
  templates/flavors/kubeadm/flatcar/patch-flatcar.yaml
Labels: bugfix
