Repository linode/cluster-api-provider-linode, pull requests merged in 2024-04, with the labels that each got.

#219 fix: add additional name validation for custom resources
  cloud/services/loadbalancers.go
  config/crd/kustomization.yaml
  config/crd/patches/validation_in_linodeclusters.yaml
  config/crd/patches/validation_in_linodeclustertemplates.yaml
  config/crd/patches/validation_in_linodemachines.yaml
  config/crd/patches/validation_in_linodemachinetemplates.yaml
  config/crd/patches/validation_in_linodevpcs.yaml
  e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
Labels: bug, go

#226 [GHA] - build and push images on main
  .github/workflows/build-push.yml
  .github/workflows/release.yml
  config/default/manager_image_patch.yaml
Labels: github_actions

#238 update workflow name in build-push job
  .github/workflows/build-push.yml
  .github/workflows/build_test_ci.yml
Labels: github_actions

#237 [GHA] check for broken links
  .github/workflows/gh-pages.yml
Labels: github_actions

#249 [GHA, docs] - Fix broken links
  .github/ISSUE_TEMPLATE.md
  .github/workflows/gh-pages.yml
  .github/workflows/link-checker.yml
  .markdownlinkcheck.json
  CONTRIBUTING.md
  docs/src/reference/reference.md
  docs/src/topics/etcd.md
  docs/src/topics/flavors/dual-stack.md
  docs/src/topics/flavors/etcd-backup-restore.md
  templates/flavors/README.md
Labels: documentation, github_actions

#247 Add tests for LinodeCluster controller
  .golangci.yml
  controller/linodecluster_controller_test.go
  controller/suite_test.go
  go.mod
  go.sum
Labels: go, testing

#256 [feat] add self-healing flavor and docs on machine health checks
  docs/src/SUMMARY.md
  docs/src/topics/backups.md
  docs/src/topics/etcd.md
  docs/src/topics/health-checking.md
  templates/addons/machine-health-check/kustomization.yaml
  templates/addons/machine-health-check/machinehealthcheck.yaml
  templates/flavors/self-healing/kustomization.yaml
Labels: documentation, feature

#258 [feat] - add new etcd-disk flavor
  docs/src/SUMMARY.md
  docs/src/topics/disks/data-disks.md
  docs/src/topics/etcd.md
  docs/src/topics/flavors/etcd-disk.md
  templates/flavors/default/kubeadmControlPlane.yaml
  templates/flavors/etcd-disk/kustomization.yaml
Labels: documentation, feature

#259 standardize k8s version and common setup steps in templates
  docs/src/topics/flavors/k3s.md
  docs/src/topics/flavors/rke2.md
  templates/common-init-files/secret.yaml
  templates/flavors/clusterclass-kubeadm/kubeadmConfigTemplate.yaml
  templates/flavors/clusterclass-kubeadm/kubeadmControlPlaneTemplate.yaml
  templates/flavors/default/kubeadmConfigTemplate.yaml
  templates/flavors/default/kubeadmControlPlane.yaml
  templates/flavors/k3s/k3sConfigTemplate.yaml
  templates/flavors/k3s/k3sControlPlane.yaml
  templates/flavors/k3s/kustomization.yaml
  templates/flavors/rke2/kustomization.yaml
  templates/flavors/rke2/rke2ConfigTemplate.yaml
  templates/flavors/rke2/rke2ControlPlane.yaml
Labels: cleanup

#251 feat: cluster autoscaler
  docs/src/SUMMARY.md
  docs/src/topics/autoscaling.md
  docs/src/topics/flavors/cluster-autoscaler.md
  templates/addons/cluster-autoscaler/cluster-autoscaler.yaml
  templates/addons/cluster-autoscaler/kustomization.yaml
  templates/flavors/cluster-autoscaler/kustomization.yaml
Labels: feature

#269 [feat] - enable cilium BGP control plane
  docs/src/topics/addons.md
  templates/addons/cilium/cilium-ipv6.yaml
  templates/addons/cilium/cilium.yaml
Labels: feature

#263 [rke2] - enable cis-profile, add configuration for CIS hardening
  docs/src/topics/flavors/rke2.md
  templates/flavors/rke2/rke2ConfigTemplate.yaml
  templates/flavors/rke2/rke2ControlPlane.yaml
Labels: documentation, rke2

#159 add vpc support for capl clusters
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  docs/src/developers/development.md
  docs/src/topics/getting-started.md
  templates/addons/cilium/cilium.yaml
  templates/addons/provider-linode/linode-ccm.yaml
  templates/common-init-files/secret.yaml
  templates/flavors/base/kustomization.yaml
  templates/flavors/base/linodeCluster.yaml
  templates/flavors/base/linodeMachineTemplate.yaml
  templates/flavors/base/linodeVPC.yaml
  templates/flavors/default/kubeadmControlPlane.yaml
  templates/flavors/k3s/k3sConfigTemplate.yaml
  templates/flavors/k3s/k3sControlPlane.yaml
  templates/flavors/k3s/secret.yaml
  templates/flavors/rke2/kustomization.yaml
  templates/flavors/rke2/rke2ConfigTemplate.yaml
  templates/flavors/rke2/rke2ControlPlane.yaml
  templates/flavors/rke2/secret.yaml
Labels: feature, go

#255 Add mocktest module
  .golangci.yml
  Makefile
  cloud/scope/client.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/common.go
  cloud/scope/common_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/scope/vpc.go
  cloud/scope/vpc_test.go
  cmd/main.go
  controller/linodemachine_controller_helpers_test.go
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragebucket_controller_test.go
  docs/src/developers/testing.md
  mock/client.go
  mock/common.go
  mock/mocktest/mock.go
  mock/mocktest/mock_test.go
  mock/mocktest/node.go
  mock/mocktest/node_test.go
  mock/mocktest/path.go
  mock/mocktest/path_test.go
  mock/mocktest/suite.go
  mock/mocktest/suite_test.go
Labels: go, testing
