Repository linode/cluster-api-provider-linode, pull requests merged in 2024-09, with the labels that each got.

#496 [feat] adding linodeFirewall to clusters
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
  templates/infra/kustomization.yaml
  templates/infra/linodeFirewall.yaml
  templates/infra/linodeMachineTemplate.yaml
Labels: new-feature

#497 [fix] : add credentials ref to linodeVPC and linodeFirewall templates
  templates/infra/linodeFirewall.yaml
  templates/infra/linodeVPC.yaml
Labels: bugfix

#500 [CI] : cleanup firewall as well in tests
  cloud/scope/firewall_test.go
  controller/linodefirewall_controller.go
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/check-child-cluster-vpc-and-firewall-deleted.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/check-child-cluster-vpc-and-firewall-deleted.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/check-child-cluster-vpc-and-firewall-deleted.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/check-child-cluster-vpc-and-firewall-deleted.yaml
Labels: repo-ci-improvement

#499 [feat] added placementGroup to full flavors
  templates/addons/placementGroups/kustomization.yaml
  templates/addons/placementGroups/linodePlacementGroup.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/full/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
Labels: new-feature

#501 [fix] handle nil firewall ID if there is an error creating the Firewall referenced
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
Labels: bugfix

#502 [fix] add default credentialsRef to bucket and key resources
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: bugfix

#498 [fix] block credentials deletion until all dependent resources are cleaned up
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  templates/infra/linodeMachineTemplate.yaml
Labels: bugfix

#504 [docs] add placement group docs and update firewall docs
  docs/src/SUMMARY.md
  docs/src/topics/firewalling.md
  docs/src/topics/placement-groups.md
Labels: documentation

#503 [improvement] add variable to set CSI chart version
  templates/addons/csi-driver-linode/linode-csi.yaml
Labels: improvement

#509 [deps] bump CAPRKE2 to use the v1beta1 spec
  e2e/capl-cluster-flavors/rke2-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
  templates/flavors/rke2/default/rke2ConfigTemplate.yaml
  templates/flavors/rke2/default/rke2ControlPlane.yaml
  templates/flavors/rke2/etcd-disk/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
Labels: dependencies

#510 [fix] disable auto-update in the flatcar flavor
  templates/flavors/kubeadm/flatcar/patch-flatcar.yaml
Labels: bugfix

#516 [deps] group all otel dependencies together
  .github/dependabot.yml
Labels: dependencies

#507 [fix] create scope with default credentials for all resources
  clients/clients.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/firewall.go
  cloud/scope/firewall_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_key.go
  cloud/scope/object_storage_key_test.go
  cloud/scope/placement_group.go
  cloud/scope/placement_group_test.go
  cloud/scope/vpc.go
  cloud/scope/vpc_test.go
  controller/linodecluster_controller.go
  controller/linodefirewall_controller.go
  controller/linodemachine_controller.go
  controller/linodeobjectstoragekey_controller.go
  controller/linodeplacementgroup_controller.go
  controller/linodevpc_controller.go
  mock/client.go
Labels: bugfix

#519 [improvement] : Limit post calls to /v4/linode/instances endpoint
  Makefile
  clients/clients.go
  cloud/scope/common.go
  cloud/scope/machine.go
  config/manager/manager.yaml
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  go.mod
  go.sum
  mock/client.go
  util/errors.go
  util/ratelimits.go
  util/ratelimits_test.go
  util/reconciler/defaults.go
Labels: improvement
