Repository linode/cluster-api-provider-linode, pull requests merged in 2024-08, with the labels that each got.

#426 [feat] Add ObjectStorageKey
  PROJECT
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/scope/object_storage_key.go
  cloud/scope/object_storage_key_test.go
  cloud/services/object_storage_buckets.go
  cloud/services/object_storage_keys.go
  cloud/services/object_storage_keys_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
  config/crd/kustomization.yaml
  config/default/manager_image_patch.yaml-e
  config/rbac/kustomization.yaml
  config/rbac/linodeobjectstoragekey_editor_role.yaml
  config/rbac/linodeobjectstoragekey_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha2_linodeobjectstoragekey.yaml
  config/samples/kustomization.yaml
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragekey_controller.go
  controller/linodeobjectstoragekey_controller_test.go
  docs/src/developers/testing.md
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/assert-capi-resources.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/assert-key-and-secret.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/check-key-and-secret-deletion.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/create-linodeobjectstoragekey.yaml
Labels: feature, go, testing, new-feature

#436 [feat] Support usage of separate Linode API for the domain client
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/common.go
  cloud/scope/common_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/scope/object_storage_key.go
  cloud/scope/object_storage_key_test.go
  cloud/scope/placement_group.go
  cloud/scope/placement_group_test.go
  cloud/scope/vpc.go
  cloud/scope/vpc_test.go
  cmd/main.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragekey_controller.go
  controller/linodeplacementgroup_controller.go
  controller/linodevpc_controller.go
  docs/src/SUMMARY.md
  docs/src/topics/flavors/dns-loadbalancing.md
  docs/src/topics/getting-started.md
  go.mod
  mock/mocktest/suite_test.go
Labels: new-feature

#437 [fix] cluster-autoscaler was pulling an incorrect image when setting up kubeadm-full
  templates/addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: bugfix

#440 [fix] : always cleanup child clusters
  .github/workflows/e2e-test.yaml
  Makefile
Labels: bugfix

#445 [CI] Update metadata.yaml with 0.6 information
  metadata.yaml
Labels: repo-ci-improvement

#444 [test]: bump Flatcar channel from Alpha to Beta
  e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
Labels: testing

#442 [improvement] add override so users can set full dns name for controlplane endpoint
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/linodecluster_webhook_test.go
  cloud/services/domains.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  docs/src/topics/flavors/dns-loadbalancing.md
  templates/flavors/k3s/dns-loadbalancing/kustomization.yaml
  templates/flavors/kubeadm/dns-loadbalancing/kustomization.yaml
  templates/flavors/kubeadm/dual-stack-dns-loadbalancing/kustomization.yaml
  templates/flavors/rke2/dns-loadbalancing/kustomization.yaml
Labels: improvement

#446 [CI] support older bash versions in generate-flavors.sh
  hack/generate-flavors.sh
Labels: repo-ci-improvement

#443 [feat] Adding new fields in LinodeObjectStorageBucket and decoupling ObjKey Functionality
  api/v1alpha1/conversion.go
  api/v1alpha1/linodeobjectstoragebucket_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/services/object_storage_buckets.go
  cloud/services/object_storage_buckets_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragebucket_controller_test.go
  controller/linodeobjectstoragekey_controller.go
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-key-secret.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-obj-and-secret.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-obj.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/check-obj-and-key-deletion.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/check-obj-deletion.yaml
Labels: new-feature

#450 [fix] bump hardcoded envtest version
  controller/suite_test.go
Labels: bugfix

#448 [feat] Update etcd-backup flavor to use LinodeObjectStorageKey
  config/rbac/role.yaml
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragebucket_controller_test.go
  controller/linodeobjectstoragekey_controller.go
  controller/linodeobjectstoragekey_controller_test.go
  docs/src/topics/etcd.md
  envrc.example
  templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: new-feature

#455 [ci] lock golangci-lint version for now
  .github/workflows/go-analyze.yml
Labels: repo-ci-improvement

#447 [test] e2e tests(konnectivity) for kubeadm-full
  .github/filters.yml
  .github/workflows/build_test_ci.yml
  .github/workflows/e2e-test.yaml
  Makefile
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-capi-resources.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-child-cluster-daemonsets.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-child-cluster-deployments.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-child-cluster-statefulsets.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-konnectivity-resources.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/check-child-cluster-and-vpc-deleted.yaml
  templates/addons/cluster-autoscaler/cluster-autoscaler.yaml
  templates/addons/konnectivity/konnectivity.yaml
Labels: testing

#451 [feat] Add LinodeFirewall controller
  .github/workflows/e2e-test.yaml
  .golangci.yml
  PROJECT
  Tiltfile
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  clients/clients.go
  cloud/scope/firewall.go
  cloud/scope/firewall_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_linodefirewalls.yaml
  config/crd/patches/webhook_in_linodefirewalls.yaml
  config/rbac/linodefirewall_editor_role.yaml
  config/rbac/linodefirewall_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha2_linodefirewall.yaml
  config/samples/kustomization.yaml
  controller/linodefirewall_controller.go
  controller/linodefirewall_controller_helpers.go
  controller/linodefirewall_controller_test.go
  e2e/linodefirewall-controller/minimal-linodefirewall/assert-capi-resources.yaml
  e2e/linodefirewall-controller/minimal-linodefirewall/assert-firewall.yaml
  e2e/linodefirewall-controller/minimal-linodefirewall/chainsaw-test.yaml
  e2e/linodefirewall-controller/minimal-linodefirewall/check-firewall-deletion.yaml
  e2e/linodefirewall-controller/minimal-linodefirewall/create-firewall.yaml
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  util/reconciler/defaults.go
Labels: new-feature

#454 [improvement] standardize predicates on controllers
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodeplacementgroup_controller.go
  controller/linodevpc_controller.go
Labels: improvement

#456 [feat] LOBJ controller updated for mutable fields LinodeObjectStorage Finalizer removed
  api/v1alpha1/conversion.go
  api/v1alpha1/linodeobjectstoragebucket_conversion_test.go
  api/v1alpha1/linodeobjectstoragebucket_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  clients/clients.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/services/object_storage_buckets.go
  cloud/services/object_storage_buckets_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragebucket_controller_test.go
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
Labels: new-feature

#462 [improvement] update install script to support newer containerd versions
  scripts/pre-kubeadminit.sh
Labels: improvement

#461 [fix] update kubeadm install script ref
  templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
  templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
Labels: bugfix

#463 [deps] update k3s provider related templates to use version v1beta2
  e2e/capl-cluster-flavors/k3s-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  templates/flavors/k3s/default/k3sConfigTemplate.yaml
  templates/flavors/k3s/default/k3sControlPlane.yaml
  templates/flavors/k3s/dual-stack/kustomization.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
Labels: dependencies

#465 [deprecation][feature] deprecate Firewall ID and add FirewallRef
  api/v1alpha1/conversion.go
  api/v1alpha1/linodemachine_conversion_test.go
  api/v1alpha1/linodemachinetemplate_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_helpers_test.go
  controller/linodemachine_controller_test.go
Labels: deprecation

#469 [deprecation] deprecate InstanceID
  api/v1alpha1/linodemachine_conversion_test.go
  api/v1alpha1/linodemachinetemplate_conversion_test.go
  api/v1alpha2/linodemachine_types.go
  cloud/services/domains_test.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  controller/linodemachine_controller.go
  controller/linodemachine_controller_test.go
  util/helpers.go
  util/helpers_test.go
Labels: deprecation

#471 [fix] fix etcd-backup-restore based flavors
  cloud/scope/object_storage_key.go
  docs/src/topics/backups.md
  templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
Labels: bugfix

#457 [fix] [improvement] move apiserver loadbalancing logic from linodemachine controller to linodecluster controller
  clients/clients.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/services/domains.go
  cloud/services/domains_test.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  cmd/main.go
  controller/linodecluster_controller.go
  controller/linodecluster_controller_helpers.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
  go.mod
  go.sum
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
Labels: bugfix, improvement

#474 [fix] revert deprecation of firewall ID
  api/v1alpha2/linodemachine_types.go
Labels: bugfix

#475 [fix] fix dns record ownership
  cloud/services/domains.go
  cloud/services/domains_test.go
  controller/linodecluster_controller_test.go
Labels: bugfix

#459 [docs] update firewall docs for Cloud Firewalls
  docs/src/topics/firewalling.md
Labels: documentation

#477 [fix] set the inbound/outbound policy to whatever was specified instead of trying to determine by policy rules
  api/v1alpha2/linodefirewall_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  controller/linodefirewall_controller_helpers.go
Labels: bugfix

#476 [feat] Support key secret templating
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/linodeobjectstoragekey_webhook.go
  api/v1alpha2/linodeobjectstoragekey_webhook_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/object_storage_key.go
  cloud/scope/object_storage_key_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
  config/crd/patches/cainjection_in_linodeobjectstoragekeys.yaml
  config/crd/patches/webhook_in_linodeobjectstoragekeys.yaml
  config/webhook/manifests.yaml
  controller/linodeobjectstoragekey_controller.go
  controller/linodeobjectstoragekey_controller_test.go
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: new-feature

#470 [cleanup] move non-reconcile functions into controller helpers
  controller/linodecluster_controller.go
  controller/linodecluster_controller_helpers.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  controller/linodevpc_controller.go
  controller/linodevpc_controller_helpers.go
Labels: cleanup

#487 [fix] remove ConditionLoadBalancing condition
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller.go
  e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
Labels: bugfix

#479 [improvement] removing v1alpha1 webhooks/deploying v1alpha2 webhooks for all resources
  api/v1alpha1/linodecluster_webhook.go
  api/v1alpha1/linodecluster_webhook_test.go
  api/v1alpha1/linodemachine_webhook.go
  api/v1alpha1/linodemachine_webhook_test.go
  api/v1alpha1/linodeobjectstoragebucket_webhook.go
  api/v1alpha1/linodeobjectstoragebucket_webhook_test.go
  api/v1alpha1/linodevpc_webhook.go
  api/v1alpha1/linodevpc_webhook_test.go
  api/v1alpha1/webhook_helpers.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/linodemachine_webhook.go
  api/v1alpha2/linodeobjectstoragebucket_webhook.go
  api/v1alpha2/linodeobjectstoragebucket_webhook_test.go
  api/v1alpha2/linodeplacementgroup_webhook.go
  api/v1alpha2/linodevpc_webhook.go
  api/v1alpha2/webhook_helpers.go
  api/v1alpha2/webhook_suite_test.go
  cmd/main.go
  config/webhook/manifests.yaml
Labels: improvement

#464 [test] E2E test for kubeadm-full ETCD
  Makefile
  e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/assert-child-cluster-statefulsets.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
Labels: testing

#485 [cleanup][improvement] Machine controller cleanup, reduce API calls for Linode instances
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  util/reconciler/defaults.go
Labels: improvement

#488 [improvement] Bump CCM version
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: improvement

#489 [fix] golangci-lint is unlocked to use the latest version again
  .github/workflows/go-analyze.yml
  .golangci.yml
  Makefile
  controller/linodecluster_controller_helpers.go
  controller/linodefirewall_controller.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodeplacementgroup_controller.go
  controller/linodevpc_controller.go
  util/reconciler/conditions.go
Labels: bugfix

#490 [fix] use protocol set by the firewall rule, add protocol validation
  api/v1alpha2/linodefirewall_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  controller/linodefirewall_controller_helpers.go
Labels: bugfix

#491 [improvement] Bump CCM to latest version
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: improvement
