Repository linode/cluster-api-provider-linode, pull requests merged in 2024-12, with the labels that each got.

#585 [deps] bump containerd and CNI plugin versions in the pre-kubeadminit script
  scripts/pre-kubeadminit.sh
Labels: dependencies

#583 [feat] - implement AddressSet CRD and support in firewall controller
  PROJECT
  Tiltfile
  api/v1alpha2/addressset_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_addressset.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_addresssets.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_addresssets.yaml
  config/crd/patches/webhook_in_addresssets.yaml
  config/rbac/addressset_editor_role.yaml
  config/rbac/addressset_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha2_addressset.yaml
  config/samples/kustomization.yaml
  docs/src/topics/firewalling.md
  e2e/linodefirewall-controller/linodefirewall-addressset/assert-addrset-firewall.yaml
  e2e/linodefirewall-controller/linodefirewall-addressset/assert-capi-resources.yaml
  e2e/linodefirewall-controller/linodefirewall-addressset/chainsaw-test.yaml
  e2e/linodefirewall-controller/linodefirewall-addressset/check-addrset-firewall-deletion.yaml
  e2e/linodefirewall-controller/linodefirewall-addressset/create-addrset-firewall.yaml
  internal/controller/linodefirewall_controller.go
  internal/controller/linodefirewall_controller_helpers.go
  internal/controller/linodefirewall_controller_helpers_test.go
  internal/controller/linodefirewall_controller_test.go
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/suite_test.go
Labels: new-feature

#586 [improvement] add cloud-init boostrap via cluster object store
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  clients/clients.go
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_key.go
  cloud/scope/object_storage_key_test.go
  cloud/services/object_storage_objects.go
  cloud/services/object_storage_objects_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
  docs/src/topics/cluster-object-store.md
  go.mod
  go.sum
  internal/controller/cloud-init.tmpl
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodeobjectstoragekey_controller_test.go
  mock/client.go
  mock/common.go
  templates/addons/cluster-object-store/cluster-object-store.yaml
  templates/addons/cluster-object-store/kustomization.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/full/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
Labels: documentation, improvement

#588 [feat][improvement][docs] implement FirewallRule CRD and support in firewall controller, remove finalizers on AddressSets
  PROJECT
  Tiltfile
  api/v1alpha2/firewallrule_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_firewallrules.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_firewallrules.yaml
  config/crd/patches/webhook_in_firewallrules.yaml
  config/rbac/firewallrule_editor_role.yaml
  config/rbac/firewallrule_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha2_firewallrule.yaml
  config/samples/kustomization.yaml
  docs/src/topics/firewalling.md
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/assert-capi-resources.yaml
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/assert-fwrule-firewall.yaml
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/chainsaw-test.yaml
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/check-fwrule-firewall-deletion.yaml
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/create-fwrule-firewall.yaml
  go.mod
  internal/controller/linodefirewall_controller.go
  internal/controller/linodefirewall_controller_helpers.go
  internal/controller/linodefirewall_controller_helpers_test.go
  internal/controller/linodefirewall_controller_test.go
Labels: documentation, new-feature, improvement

#591 [CI] Update metadata.yaml for 0.8.0 release
  metadata.yaml
Labels: repo-ci-improvement

#589 [improvement] Remove severity levels from controller logic
  internal/controller/linodecluster_controller.go
  internal/controller/linodefirewall_controller.go
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodeobjectstoragebucket_controller.go
  internal/controller/linodeplacementgroup_controller.go
  internal/controller/linodevpc_controller.go
  util/reconciler/conditions.go
Labels: improvement

#590 [improvement] Change conditions pkg to use kubernetes metav1
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/linodeplacementgroup_types.go
  api/v1alpha2/linodevpc_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeplacementgroups.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  go.mod
  go.sum
  internal/controller/linodecluster_controller.go
  internal/controller/linodecluster_controller_test.go
  internal/controller/linodefirewall_controller.go
  internal/controller/linodefirewall_controller_test.go
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodeobjectstoragebucket_controller.go
  internal/controller/linodeobjectstoragebucket_controller_test.go
  internal/controller/linodeobjectstoragekey_controller.go
  internal/controller/linodeobjectstoragekey_controller_test.go
  internal/controller/linodeplacementgroup_controller.go
  internal/controller/linodevpc_controller.go
  internal/controller/linodevpc_controller_test.go
  util/errors.go
  util/reconciler/conditions.go
Labels: improvement

#602 [ci][deps] pin capi operator version, skip e2e tests for markdown-only changes
  .github/workflows/build_test_ci.yml
  .github/workflows/e2e-test.yaml
  Tiltfile
Labels: dependencies, repo-ci-improvement

#603 [fix] disk_setup for additional user data in RKE2
  templates/flavors/rke2/etcd-disk/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
Labels: bugfix

#604 [CI] : allow ingest.codecov.io so that codecov can work properly
  .github/workflows/build_test_ci.yml
Labels: repo-ci-improvement
