Repository linode/cluster-api-provider-linode, pull requests merged in 2024-02, with the labels that each got.

#138 move kubeadm specific config into default
  templates/flavors/base/cluster.yaml
  templates/flavors/base/kustomization.yaml
  templates/flavors/base/linode-machine-template.yaml
  templates/flavors/base/machine-deployment.yaml
  templates/flavors/default/kubeadm-control-plane.yaml
  templates/flavors/default/kustomization.yaml
  templates/flavors/default/linode-machine-template.yaml
Labels: cleanup

#141 change nodenames to lowercase
  e2e/linodevpc-controller/minimal/03-verify-vpc.yaml
  util/helpers.go
Labels: bug

#139 add k3s flavor support
  docs/src/flavors/clusterclass-kubeadm.md
  docs/src/flavors/default.md
  docs/src/flavors/flavors.md
  docs/src/flavors/k3s.md
  docs/src/topics/getting-started.md
  templates/flavors/README.md
  templates/flavors/k3s/k3sConfigTemplate.yaml
  templates/flavors/k3s/k3sControlPlane.yaml
  templates/flavors/k3s/kustomization.yaml
  templates/flavors/k3s/secret.yaml
Labels: feature

#147 set ipam mode to kubernetes
  docs/src/flavors/clusterclass-kubeadm.md
  templates/addons/cilium/cilium.yaml
  templates/flavors/base/cluster.yaml
  templates/flavors/clusterclass-kubeadm/cluster-template.yaml
Labels: bug

#148 Update README.md with alpha warning
  README.md
Labels: documentation

#144 Add rke2 flavor support
  docs/src/SUMMARY.md
  docs/src/topics/flavors/clusterclass-kubeadm.md
  docs/src/topics/flavors/default.md
  docs/src/topics/flavors/flavors.md
  docs/src/topics/flavors/k3s.md
  docs/src/topics/flavors/rke2.md
  templates/flavors/rke2/kustomization.yaml
  templates/flavors/rke2/rke2ConfigTemplate.yaml
  templates/flavors/rke2/rke2ControlPlane.yaml
  templates/flavors/rke2/secret.yaml
Labels: documentation, feature

#153 🧹 [cleanup] restructure template directories for additional clusterclasses
  hack/generate-flavors.sh
  templates/addons/cluster-resource-set/kustomization.yaml
  templates/common-init-files/kustomization.yaml
  templates/flavors/base/kustomization.yaml
  templates/flavors/base/linodeCluster.yaml
  templates/flavors/base/linodeMachineTemplate.yaml
  templates/flavors/base/machineDeployment.yaml
  templates/flavors/clusterclass-base/kustomization.yaml
  templates/flavors/clusterclass-base/linodeClusterTemplate.yaml
  templates/flavors/clusterclass-base/linodeMachineControlPlaneTemplate.yaml
  templates/flavors/clusterclass-base/linodeMachineWorkerTemplate.yaml
  templates/flavors/clusterclass-kubeadm/clusterClass.yaml
  templates/flavors/clusterclass-kubeadm/kubeadmConfigTemplate.yaml
  templates/flavors/clusterclass-kubeadm/kubeadmControlPlaneTemplate.yaml
  templates/flavors/clusterclass-kubeadm/kustomization.yaml
  templates/flavors/default/kubeadmConfigTemplate.yaml
  templates/flavors/default/kubeadmControlPlane.yaml
  templates/flavors/default/kustomization.yaml
  templates/flavors/k3s/kustomization.yaml
  templates/flavors/rke2/kustomization.yaml
Labels: cleanup

#157 🔧 [tweak] - use different k8s version vars for different flavors
  docs/src/topics/flavors/k3s.md
  docs/src/topics/flavors/rke2.md
  templates/flavors/k3s/k3sControlPlane.yaml
  templates/flavors/k3s/kustomization.yaml
  templates/flavors/rke2/kustomization.yaml
  templates/flavors/rke2/rke2ConfigTemplate.yaml
  templates/flavors/rke2/rke2ControlPlane.yaml
Labels: documentation, cleanup

#145 [feat] Add deleteBucket logic for Linode OBJ
  cloud/scope/object_storage_bucket.go
  cloud/services/object_storage_buckets.go
  config/samples/infrastructure_v1alpha1_linodeobjectstoragebucket.yaml
  controller/linodeobjectstoragebucket_controller.go
Labels: feature, obj
