Repository linode/cluster-api-provider-linode, pull requests merged in 2024-07, with the labels that each got.

#388 [fix] : fix konnectivity installs as we are now installing packages from tar files
  templates/flavors/kubeadm/konnectivity/kustomization.yaml
Labels: bugfix

#393 [fix] bug where v1alpha1/2 linodecluster webhooks have same auto-generated name
  api/v1alpha1/linodecluster_webhook.go
  api/v1alpha1/linodemachine_webhook.go
  api/v1alpha1/linodeobjectstoragebucket_webhook.go
  api/v1alpha1/linodevpc_webhook.go
  api/v1alpha2/linodecluster_webhook.go
  config/webhook/manifests.yaml
Labels: bugfix

#395 [fix] add support for filling in controlPlaneEndpoint if only network info is specified
  clients/clients.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
Labels: bugfix

#390 [fix] allow linodemachine controller to recreate linode on delete
  cloud/services/domains.go
  cloud/services/domains_test.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
Labels: bugfix

#401 [CI] group otel deps together in dependabot
  .github/dependabot.yml
Labels: repo-ci-improvement

#406 [improvement] [test] [docs] add dns webook and flavor docs
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/linodecluster_webhook_test.go
  docs/src/topics/flavors/dns-loadbalancing.md
Labels: documentation, testing, improvement

#407 [feat] add controller concurrency options with elevated defaults
  cmd/main.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodeobjectstoragebucket_controller.go
  controller/linodevpc_controller.go
  observability/wrappers/interfaces.go
Labels: new-feature

#410 [improvement] : update ccm-linode to v0.4.10
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: improvement

#408 [fix] handle requeues for linode api errors on update and delete, set instance ID if linode already exists
  cmd/main.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_test.go
Labels: bugfix

#414 [feat] linode placement groups - boilerplate + controllers + e2e tests
  .github/workflows/e2e-test.yaml
  PROJECT
  Tiltfile
  api/v1alpha2/linodeplacementgroup_types.go
  api/v1alpha2/linodeplacementgroup_webhook.go
  api/v1alpha2/linodeplacementgroup_webhook_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  clients/clients.go
  cloud/scope/placement_group.go
  cloud/scope/placement_group_test.go
  cloud/scope/vpc.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeplacementgroups.yaml
  config/crd/kustomization.yaml
  config/crd/patches/validation_in_linodeplacementgroups.yaml
  config/crd/patches/webhook_in_linodeplacementgroups.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha2_linodeplacementgroup.yaml
  config/webhook/manifests.yaml
  controller/linodeplacementgroup_controller.go
  controller/linodeplacementgroup_controller_helpers.go
  controller/linodeplacementgroup_controller_test.go
  controller/linodevpc_controller.go
  e2e/admission-webhooks/validating/chainsaw-test.yaml
  e2e/admission-webhooks/validating/invalid-linodeplacementgroup.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/assert-capi-resources.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/assert-placementgroup.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/chainsaw-test.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/check-placementgroup-deletion.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/create-placementgroup.yaml
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  util/reconciler/defaults.go
Labels: new-feature

#417 [deps] linodego update from 1.36.2 to 1.37.0
  clients/clients.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/services/object_storage_buckets.go
  controller/linodeobjectstoragebucket_controller_test.go
  go.mod
  go.sum
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
Labels: dependencies

#416 [feat] add a v1alpha2 version of LinodeMachine
  PROJECT
  api/v1alpha1/linodemachine_conversion.go
  api/v1alpha1/linodemachine_conversion_test.go
  api/v1alpha2/linodemachine_conversion.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodemachine_webhook.go
  api/v1alpha2/linodemachine_webhook_test.go
  api/v1alpha2/webhook_helpers.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/kustomization.yaml
  config/rbac/kustomization.yaml
  config/samples/infrastructure_v1alpha2_linodemachine.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  controller/linodemachine_controller.go
  e2e/admission-webhooks/validating/invalid-linodemachine.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/check-child-cluster-and-vpc-deleted.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/check-child-cluster-and-vpc-deleted.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/check-child-cluster-and-vpc-deleted.yaml
  e2e/linodemachine-controller/minimal-linodemachine/assert-linodemachine.yaml
  e2e/linodemachine-controller/minimal-linodemachine/check-linodemachine-deletion.yaml
  e2e/linodemachine-controller/vpc-integration/assert-linodemachine.yaml
  e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/vpc-integration/check-vpc-lm-deletion.yaml
Labels: new-feature

#419 [feat] Add support for using Akamai EDGE DNS as DNS Provider for API Server Loadbalancing
  .github/workflows/e2e-test.yaml
  Tiltfile
  api/v1alpha2/linodecluster_types.go
  clients/clients.go
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/services/domains.go
  cloud/services/domains_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/default/akamai-edgerc-secret.yaml
  config/default/kustomization.yaml
  config/default/manager_credentials_patch.yaml
  config/manager/manager.yaml
  docs/src/topics/flavors/dns-loadbalancing.md
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/chainsaw-test.yaml
  go.mod
  go.sum
  mock/client.go
  mock/common.go
  templates/flavors/k3s/dns-loadbalancing/kustomization.yaml
  templates/flavors/kubeadm/dns-loadbalancing/kustomization.yaml
  templates/flavors/kubeadm/dual-stack-dns-loadbalancing/kustomization.yaml
  templates/flavors/rke2/dns-loadbalancing/kustomization.yaml
Labels: new-feature

#421 [feat] add v1alpha2 of linodeVPC
  PROJECT
  api/v1alpha1/linodevpc_conversion.go
  api/v1alpha1/linodevpc_conversion_test.go
  api/v1alpha2/linodevpc_conversion.go
  api/v1alpha2/linodevpc_types.go
  api/v1alpha2/linodevpc_webhook.go
  api/v1alpha2/linodevpc_webhook_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/common_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/vpc.go
  cloud/scope/vpc_test.go
  cloud/services/domains_test.go
  cloud/services/loadbalancers_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  config/crd/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/linodevpc_editor_role.yaml
  config/rbac/linodevpc_viewer_role.yaml
  config/samples/infrastructure_v1alpha2_linodevpc.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_helpers_test.go
  controller/linodemachine_controller_test.go
  controller/linodevpc_controller.go
  controller/linodevpc_controller_helpers.go
  controller/linodevpc_controller_helpers_test.go
  controller/linodevpc_controller_test.go
  docs/src/developers/testing.md
  mock/mocktest/path_test.go
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
  templates/infra/linodeCluster.yaml
  templates/infra/linodeVPC.yaml
Labels: new-feature

#422 [fix] account for retryable errors
  controller/linodemachine_controller.go
  util/helpers.go
  util/helpers_test.go
Labels: bugfix

#425 [feat] add v1alpha2 of linodeClusterTemplate
  Makefile
  PROJECT
  api/v1alpha1/conversion.go
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/linodeclustertemplate_conversion.go
  api/v1alpha1/linodeclustertemplate_conversion_test.go
  api/v1alpha1/webhook_helpers.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodeclustertemplate_conversion.go
  api/v1alpha2/linodeclustertemplate_types.go
  api/v1alpha2/linodeclustertemplate_webhook.go
  api/v1alpha2/linodeclustertemplate_webhook_test.go
  api/v1alpha2/webhook_helpers.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  config/crd/kustomization.yaml
  config/rbac/kustomization.yaml
  config/samples/infrastructure_v1alpha2_linodeclustertemplate.yaml
  config/samples/kustomization.yaml
Labels: new-feature

#424 [fix] Fix create/update opertions if leftover DNS entries are found
  cloud/services/domains.go
  cloud/services/domains_test.go
Labels: bugfix

#428 [feat] add v1alpha2 of linodeMachineTemplate
  .golangci.yml
  PROJECT
  api/v1alpha1/linodeclustertemplate_conversion.go
  api/v1alpha1/linodemachinetemplate_conversion.go
  api/v1alpha1/linodemachinetemplate_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodemachinetemplate_conversion.go
  api/v1alpha2/linodemachinetemplate_types.go
  api/v1alpha2/linodemachinetemplate_webhook.go
  api/v1alpha2/linodemachinetemplate_webhook_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  config/crd/kustomization.yaml
  config/rbac/kustomization.yaml
  config/samples/infrastructure_v1alpha2_linodemachinetemplate.yaml
  config/samples/kustomization.yaml
  e2e/admission-webhooks/validating/chainsaw-test.yaml
  e2e/admission-webhooks/validating/invalid-linodevpc.yaml
  e2e/linodevpc-controller/minimal-linodevpc/assert-vpc.yaml
  e2e/linodevpc-controller/minimal-linodevpc/chainsaw-test.yaml
  e2e/linodevpc-controller/minimal-linodevpc/check-vpc-deletion.yaml
  e2e/linodevpc-controller/minimal-linodevpc/create-vpc.yaml
  templates/flavors/clusterclass-kubeadm/clusterClass.yaml
  templates/flavors/clusterclass-kubeadm/deleteTransformer.yaml
  templates/flavors/clusterclass-kubeadm/kustomization.yaml
  templates/flavors/clusterclass-kubeadm/linodeClusterTemplate.yaml
  templates/flavors/k3s/default/k3sControlPlane.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/linodeMachineTemplate.yaml
  templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
  templates/flavors/kubeadm/etcd-disk/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/rke2/default/rke2ControlPlane.yaml
  templates/flavors/rke2/etcd-disk/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
  templates/infra/linodeMachineTemplate.yaml
  templates/infra/machineDeployment.yaml
Labels: new-feature

#429 [feat] migrate manual conversions to conversion-gen
  api/v1alpha1/linodecluster_conversion.go
  api/v1alpha1/linodecluster_conversion_test.go
  api/v1alpha1/linodeclustertemplate_conversion_test.go
  api/v1alpha1/linodemachine_conversion.go
  api/v1alpha1/linodemachine_conversion_test.go
  api/v1alpha1/linodemachinetemplate_conversion_test.go
  api/v1alpha1/linodevpc_conversion.go
  api/v1alpha1/linodevpc_conversion_test.go
  api/v1alpha2/linodecluster_conversion.go
  api/v1alpha2/linodemachine_conversion.go
  api/v1alpha2/linodevpc_conversion.go
Labels: new-feature

#418 [feat] Add PlacementGroupRef to linodeMachine
  .github/workflows/e2e-test.yaml
  api/v1alpha1/conversion.go
  api/v1alpha1/linodemachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodeplacementgroup_types.go
  api/v1alpha2/linodeplacementgroup_webhook.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeplacementgroups.yaml
  config/crd/patches/capicontract_in_linodeclustertemplates.yaml
  config/crd/patches/capicontract_in_linodemachines.yaml
  config/crd/patches/capicontract_in_linodemachinetemplates.yaml
  config/crd/patches/capicontract_in_linodevpcs.yaml
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  controller/linodeplacementgroup_controller_test.go
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/chainsaw-test.yaml
  go.mod
  go.sum
  templates/flavors/clusterclass-kubeadm/kustomization.yaml
  templates/flavors/kubeadm/etcd-disk/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/rke2/etcd-disk/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
Labels: new-feature

#435 [fix] add move-heirarchy label to LMT
  api/v1alpha1/linodemachinetemplate_types.go
  api/v1alpha2/linodemachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
Labels: bugfix

#427 [feat] add a v1alpha2 version of LinodeObjectStorageBucket
  PROJECT
  api/v1alpha1/conversion.go
  api/v1alpha1/linodeobjectstoragebucket_conversion.go
  api/v1alpha1/linodeobjectstoragebucket_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/linodeobjectstoragebucket_conversion.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/linodeobjectstoragebucket_webhook.go
  api/v1alpha2/linodeobjectstoragebucket_webhook_test.go
  api/v1alpha2/webhook_helpers.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/services/object_storage_buckets.go
  cloud/services/object_storage_buckets_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/capicontract_in_linodeobjectstoragebuckets.yaml
  config/rbac/kustomization.yaml
  config/samples/infrastructure_v1alpha2_linodeobjectstoragebucket.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragebucket_controller_test.go
  docs/src/topics/backups.md
  docs/src/topics/multi-tenancy.md
  e2e/admission-webhooks/validating/invalid-linodeobjectstoragebucket.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/create-linodemachine.yaml
  e2e/linodemachine-controller/vpc-integration/assert-vpc.yaml
  e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/vpc-integration/check-vpc-lm-deletion.yaml
  e2e/linodemachine-controller/vpc-integration/create-cluster-vpc.yaml
  e2e/linodemachine-controller/vpc-integration/create-linodemachine.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-keygen.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-obj-and-secret.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/check-obj-and-key-deletion.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/create-linodeobjectstoragebucket.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/patch-obj.yaml
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: new-feature
