Repository linode/cluster-api-provider-linode, pull requests merged in 2024-05, with the labels that each got.

#330 [feat]: linodeobjectstoragebucket: add validating admission webhook on create
  PROJECT
  api/v1alpha1/linodeobjectstoragebucket_webhook.go
  api/v1alpha1/linodeobjectstoragebucket_webhook_test.go
  api/v1alpha1/webhook_helpers.go
  api/v1alpha1/webhook_suite_test.go
  cmd/main.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_linodeobjectstoragebuckets.yaml
  config/crd/patches/webhook_in_linodeobjectstoragebuckets.yaml
  config/webhook/manifests.yaml
Labels: new-feature

#332 [ci] fix drafter branch
  .github/workflows/release-drafter.yml
Labels: repo-ci-improvement

#334 [fix] revert "chore: add webhook toggle"
  Makefile
  Tiltfile
  config/default/.gitignore
  config/default/kustomization.yaml
  config/default/manager-configmap.yaml
  config/default/manager_webhook_patch.yaml
Labels: bugfix

#336 [fix] bugfix: add braces to ssh key env var in machine template
  templates/infra/linodeMachineTemplate.yaml
Labels: bugfix

#328 [CI] e2e: add validating admission webhooks test
  e2e/admission-webhooks/validating/assert-capl-resources.yaml
  e2e/admission-webhooks/validating/chainsaw-test.yaml
  e2e/admission-webhooks/validating/invalid-linodecluster.yaml
  e2e/admission-webhooks/validating/invalid-linodemachine.yaml
  e2e/admission-webhooks/validating/invalid-linodeobjectstoragebucket.yaml
  e2e/admission-webhooks/validating/invalid-linodevpc.yaml
Labels: repo-ci-improvement

#342 [improvement]: add static files required by kubeadm using script than cloud-init
  scripts/add-kubeadm-required-files.sh
Labels: improvement

#335 [CI]: create a test matrix based on template paths
  .github/filters.yml
  .github/workflows/build_test_ci.yml
  .github/workflows/e2e-test.yaml
  .github/workflows/go-analyze.yml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/assert-capi-resources.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/assert-child-cluster-daemonsets.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/assert-child-cluster-deployments.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/assert-child-cluster-resources.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/check-child-cluster-and-vpc-deleted.yaml
  templates/flavors/kubeadm/default/kustomization.yaml
Labels: repo-ci-improvement

#313 [feat]: add support for a debug deploy option using delve
  .dockerignore
  Tiltfile
  config/manager/manager.yaml
  docs/src/developers/development.md
Labels: new-feature

#343 [improvement]: reduce cloud-init size, use script for kubeadm
  templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
  templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
Labels: improvement

#344 [docs] Add docs for new flavors
  docs/src/topics/flavors/cluster-autoscaler.md
  docs/src/topics/flavors/dual-stack.md
  docs/src/topics/flavors/etcd-backup-restore.md
  docs/src/topics/flavors/etcd-disk.md
  docs/src/topics/flavors/flavors.md
  docs/src/topics/flavors/vpcless.md
Labels: documentation

#345 [deps] upgrade devbox/Makefile tools versions to the latest versions
  Makefile
  devbox.json
  devbox.lock
Labels: dependencies

#348 [fix] Create new ccnp for etcd ports
  templates/addons/cilium-network-policies/ciliumNetworkPolicies.yaml
  templates/flavors/kubeadm/default/allow-etcd-policy.yaml
  templates/flavors/kubeadm/default/kustomization.yaml
Labels: bugfix

#347 [docs] clean up documentation based on latest clusterctl release
  .github/filters.yml
  .github/workflows/build_test_ci.yml
  docs/src/developers/development.md
  docs/src/developers/testing.md
  docs/src/topics/getting-started.md
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
  e2e/gha-clusterctl-config.yaml
  templates/flavors/k3s/default/k3sControlPlane.yaml
  templates/flavors/k3s/default/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/rke2/default/kustomization.yaml
  templates/flavors/rke2/default/rke2ControlPlane.yaml
  templates/flavors/rke2/default/secret.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
Labels: documentation

#350 [deps] addons/csi-driver-linode: Bump to v0.7.0
  templates/addons/csi-driver-linode/linode-csi.yaml
Labels: dependencies
