Repository linode/cluster-api-provider-linode, pull requests merged in 2024-03, with the labels that each got.

#156 [fix] [rke2] - set node-ip, use internal-only-ips for rke2 registration, set the ip type properly for the machine addresses
  controller/linodemachine_controller.go
  templates/flavors/rke2/rke2ConfigTemplate.yaml
  templates/flavors/rke2/rke2ControlPlane.yaml
Labels: bug, go, rke2

#142 feat: multi-tenancy
  api/v1alpha1/linodecluster_types.go
  api/v1alpha1/linodevpc_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/vpc.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodevpc_controller.go
  docs/src/SUMMARY.md
  docs/src/developers/development.md
  docs/src/topics/multi-tenancy.md
  templates/flavors/base/linodeCluster.yaml
  templates/flavors/base/secret.yaml
Labels: documentation, feature, go

#164 Add label field to OBJ bucket
  api/v1alpha1/linodeobjectstoragebucket_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cloud/scope/object_storage_bucket.go
  cloud/services/object_storage_buckets.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  controller/linodeobjectstoragebucket_controller.go
Labels: go, obj

#167 support byovpc and clean up list filtering
  .github/workflows/build_test_ci.yml
  .github/workflows/codeql.yml
  api/v1alpha1/linodecluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cloud/services/loadbalancers.go
  cloud/services/object_storage_buckets.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodevpc_controller.go
  controller/linodevpc_controller_helpers.go
  util/filter.go
  util/helpers.go
Labels: go, cleanup

#173 [dev tweak] - install rke2 and k3s providers in tilt cluster if env vars are set, update dev docs
  Tiltfile
  docs/src/developers/development.md
Labels: documentation

#172 🧹 [cleanup] golangci-lint updates
  .golangci.yml
  cloud/scope/object_storage_bucket.go
  cloud/services/loadbalancers.go
  cloud/services/object_storage_buckets.go
  cmd/main.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodeobjectstoragebucket_controller.go
  controller/linodevpc_controller.go
  controller/linodevpc_controller_helpers.go
  controller/suite_test.go
Labels: cleanup

#178 [GHA] - force log upload to overwrite existing logs
  .github/workflows/build_test_ci.yml
Labels: github_actions

#174 🧹 [cleanup] - refactoring to reduce cyclomatic complexity in machine controller, add missing autogenerated changes
  .golangci.yml
  api/v1alpha1/zz_generated.deepcopy.go
  cloud/services/loadbalancers.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
Labels: go, cleanup

#168 Unit tests for cloud/scope/common.go
  Makefile
  cloud/scope/client.go
  cloud/scope/common.go
  cloud/scope/common_test.go
  devbox.json
  devbox.lock
  go.mod
  go.sum
  mock/client.go
Labels: go, testing

#176 Add Unit tests for cloud/scope/cluster.go
  cloud/scope/client.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  controller/linodecluster_controller.go
  go.mod
  mock/client.go
  util/helpers.go
Labels: go, testing

#180 Unit tests for cloud/scope/machine.go
  cloud/scope/cluster.go
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  controller/linodemachine_controller.go
Labels: testing

#181 Migrate from kuttl to chainsaw
  .github/workflows/build_test_ci.yml
  Makefile
  cloud/services/object_storage_buckets.go
  controller/linodeobjectstoragebucket_controller.go
  docs/src/developers/testing.md
  e2e/Makefile
  e2e/README.MD
  e2e/kind-config.yaml
  e2e/kuttl-config.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/00-ensure-no-bucket.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/01-assert.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/01-create-linodeobjectstoragebucket.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/02-verify-bucket-and-secret.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/03-assert.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/03-patch-bucket.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/04-delete-linodeobjectstoragebucket.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/05-errors.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/Makefile
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
  e2e/linodevpc-controller/minimal-linodevpc/01-assert.yaml
  e2e/linodevpc-controller/minimal-linodevpc/01-create-vpc.yaml
  e2e/linodevpc-controller/minimal-linodevpc/02-verify-vpc.yaml
  e2e/linodevpc-controller/minimal-linodevpc/03-delete-vpc.yaml
  e2e/linodevpc-controller/minimal-linodevpc/03-error.yaml
  e2e/linodevpc-controller/minimal-linodevpc/04-verify-no-vpc.yaml
  e2e/linodevpc-controller/minimal-linodevpc/Makefile
  e2e/linodevpc-controller/minimal-linodevpc/chainsaw-test.yaml
Labels: github_actions, testing

#182 Add Unit tests for cloud/scope/vpc.go
  cloud/scope/client.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/vpc.go
  cloud/scope/vpc_test.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  devbox.lock
  mock/client.go
  util/helpers.go
Labels: testing

#187 Add Unit test for cloud/scope/obj
  cloud/scope/cluster_test.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
Labels: go, obj, testing

#193 [GHA] - add new target to catch uncommitted generated files in GHA, make sure to generate-mock target before testing
  .github/workflows/build_test_ci.yml
  Makefile
Labels: github_actions

#195 [BUG] - Improved error handling to avoid nil ptrs
  cloud/services/loadbalancers.go
  cloud/services/object_storage_buckets.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodeobjectstoragebucket_controller.go
  devbox.lock
Labels: bug

#196 Add Unit tests for cloud/service/loadbalancer
  cloud/scope/client.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  mock/client.go
Labels: go, testing

#205 Add unit test for cloud/service/obj
  cloud/services/object_storage_buckets_test.go
Labels: go, obj, testing

#212 [fix] - wait up to 30 seconds for root disk to resize
  cloud/scope/client.go
  controller/linodemachine_controller.go
  mock/client.go
Labels: bug, go

#209 Install etcd-backup-restore for child clusters
  Makefile
  api/v1alpha1/linodeobjectstoragebucket_types.go
  cloud/scope/object_storage_bucket.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  controller/linodeobjectstoragebucket_controller_test.go
  templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
  templates/addons/etcd-backup-restore/kustomization.yaml
  templates/addons/etcd-backup-restore/linode-obj.yaml
  templates/addons/etcd-backup-restore/sse-key-secret.yaml
  templates/flavors/etcd-backup-restore/kustomization.yaml
Labels: feature, obj

#213 [doc] OBJ resource usage
  controller/linodeobjectstoragebucket_controller_test.go
  docs/src/SUMMARY.md
  docs/src/topics/backups.md
  docs/src/topics/getting-started.md
  docs/src/topics/multi-tenancy.md
Labels: documentation, obj

#221 Add docs for etcd backups and set default for etcd backup restore image
  docs/src/topics/backups.md
  docs/src/topics/etcd.md
  docs/src/topics/flavors/etcd-backup-restore.md
Labels: documentation

#222 [docs] - update docs
  docs/src/developers/development.md
  docs/src/topics/flavors/default.md
  docs/src/topics/flavors/flavors.md
Labels: documentation

#218 Use URL from linodego create response for etcd-backup endpoint
  api/v1alpha1/linodeobjectstoragebucket_types.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
  controller/linodeobjectstoragebucket_controller.go
  controller/linodeobjectstoragebucket_controller_test.go
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
  templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: go, obj, testing
