Repository linode/cluster-api-provider-linode, pull requests merged in 2024-06, with the labels that each got.

#349 [fix] cert hostpath and kustomize patch & label fixes for flavors
  .github/workflows/e2e-test.yaml
  Makefile
  hack/generate-flavors.sh
  templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/full/kustomization.yaml
  templates/flavors/kubeadm/etcd-disk/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
Labels: bugfix

#353 [fix] Add patch for configtemplate for k3s for node-ip
  templates/flavors/k3s/dual-stack/kustomization.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
Labels: bugfix

#354 [fix] flavors beside clusterclass that were missing cilium host FW
  templates/flavors/k3s/dual-stack/kustomization.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/kubeadm/dual-stack/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
Labels: bugfix

#351 [feat]: bump version for linodecluster to v1alpha2
  PROJECT
  api/v1alpha1/linodecluster_conversion.go
  api/v1alpha1/linodecluster_conversion_test.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/linodecluster_conversion.go
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/linodecluster_webhook_test.go
  api/v1alpha2/webhook_helpers.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/common_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_infrastructure_linodeclusters.yaml
  config/crd/patches/capicontract_in_linodeclusters.yaml
  config/crd/patches/capicontract_in_linodeclustertemplates.yaml
  config/crd/patches/capicontract_in_linodemachines.yaml
  config/crd/patches/capicontract_in_linodemachinetemplates.yaml
  config/crd/patches/capicontract_in_linodeobjectstoragebuckets.yaml
  config/crd/patches/capicontract_in_linodevpcs.yaml
  config/crd/patches/webhook_in_infrastructure_linodeclusters.yaml
  config/rbac/infrastructure_linodecluster_editor_role.yaml
  config/rbac/infrastructure_linodecluster_viewer_role.yaml
  config/samples/infrastructure_v1alpha2_linodecluster.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_helpers.go
  controller/linodemachine_controller_test.go
  controller/suite_test.go
  docs/src/SUMMARY.md
  e2e/linodecluster-controller/minimal-linodecluster/assert-linodecluster.yaml
  e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
  e2e/linodecluster-controller/minimal-linodecluster/check-linodecluster-deleted.yaml
  e2e/linodecluster-controller/minimal-linodecluster/create-cluster.yaml
  e2e/linodecluster-controller/minimal-linodecluster/create-linodecluster.yaml
  e2e/linodemachine-controller/minimal-linodemachine/create-cluster.yaml
  e2e/linodemachine-controller/vpc-integration/create-cluster-vpc.yaml
  templates/flavors/clusterclass-kubeadm/deleteTransformer.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
  templates/infra/cluster.yaml
  templates/infra/linodeCluster.yaml
Labels: new-feature

#317 [feat] [deps]: New flavor for Cilium BGP load-balancing for Services, bump linode-CCM version
  .github/filters.yml
  docs/src/SUMMARY.md
  docs/src/topics/flavors/cilium-bgp-lb.md
  templates/addons/ccm-linode/ccm-linode.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/kubeadmConfigTemplate.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/kustomization.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/linodeMachineTemplate.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/machineDeployment.yaml
Labels: dependencies, new-feature

#356 [feat] Adding prometheus and grafana to observe various capl metrics and performance
  .markdownlinkcheck.json
  Tiltfile
  config/default/kustomization.yaml
  config/prometheus/controller-runtime-dashboard.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  hack/observability/prometheus/values.yaml
  hack/observability/readme.md
Labels: new-feature

#357 [fix]: fix version of linodecluster to correctly patch targets
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
Labels: bugfix

#358 [improvement]: move vpc interface to eth0
  controller/linodemachine_controller_helpers.go
  docs/src/topics/firewalling.md
  docs/src/topics/vpc.md
  templates/addons/cilium/cilium.yaml
  templates/flavors/k3s/default/k3sConfigTemplate.yaml
  templates/flavors/k3s/default/k3sControlPlane.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
  templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
  templates/flavors/kubeadm/default/kustomization.yaml
  templates/flavors/kubeadm/vpcless/allow-etcd-policy.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
  templates/flavors/rke2/default/rke2ConfigTemplate.yaml
  templates/flavors/rke2/default/rke2ControlPlane.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
  templates/infra/linodeMachineTemplate.yaml
Labels: improvement

#364 [fix] finalizers to not contain the apiVersion
  api/v1alpha1/linodecluster_types.go
  api/v1alpha1/linodemachine_types.go
  api/v1alpha1/linodeobjectstoragebucket_types.go
  api/v1alpha1/linodevpc_types.go
  api/v1alpha2/linodecluster_types.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/scope/vpc.go
  cloud/scope/vpc_test.go
  controller/linodecluster_controller.go
  controller/linodemachine_controller.go
  controller/linodeobjectstoragebucket_controller.go
  controller/linodevpc_controller.go
  e2e/linodecluster-controller/minimal-linodecluster/assert-linodecluster.yaml
Labels: bugfix

#355 [feat]: add konnectivity flavor for kubeadm
  .github/filters.yml
  api/v1alpha1/linodecluster_conversion.go
  api/v1alpha1/linodecluster_conversion_test.go
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodecluster_webhook_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  controller/linodecluster_controller.go
  docs/src/SUMMARY.md
  docs/src/topics/flavors/flavors.md
  docs/src/topics/flavors/konnectivity.md
  templates/addons/konnectivity/konnectivity.yaml
  templates/addons/konnectivity/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/kubeadm/konnectivity/kustomization.yaml
Labels: new-feature

#366 [cleanup] switch to not using apt for kubeadm, kubelet, and kubectl, curl kubeadm pre-init script
  .github/workflows/release.yml
  scripts/add-kubeadm-required-files.sh
  scripts/pre-kubeadminit.sh
  templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
  templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
Labels: cleanup

#371 [fix]: fix vpcless installs when firewalling is enabled
  templates/addons/ccm-linode/ccm-linode.yaml
  templates/addons/cilium-network-policies/ciliumNetworkPolicies.yaml
  templates/flavors/kubeadm/konnectivity/kustomization.yaml
  templates/flavors/kubeadm/vpcless/allow-etcd-policy.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
Labels: bugfix

#372 [feat] add distributed tracing using OTEL
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  api/v1alpha1/linodecluster_webhook.go
  api/v1alpha1/linodemachine_webhook.go
  api/v1alpha1/linodeobjectstoragebucket_webhook.go
  api/v1alpha1/linodevpc_webhook.go
  api/v1alpha1/webhook_helpers.go
  api/v1alpha2/linodecluster_webhook.go
  api/v1alpha2/webhook_helpers.go
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/scope/vpc.go
  cmd/main.go
  cmd/main_test.go
  codecov.yml
  docs/src/topics/distributed-tracing.md
  go.mod
  go.sum
  hack/templates/opentelemetry.go.gotpl
  observability/tracing/tracing.go
  observability/tracing/tracing_test.go
  observability/wrappers/interfaces.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  observability/wrappers/reconciler/reconciler.gen.go
Labels: new-feature

#374 [fix] update linodeobj and autoscaler template defaults
  templates/addons/cluster-autoscaler/cluster-autoscaler.yaml
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: bugfix

#376 [improvement] OTEL semconv update
  cmd/main.go
  config/manager/manager.yaml
Labels: improvement

#370 [feat] DNS based LoadBalancing for the CAPL cluster API Server
  .gitignore
  .golangci.yml
  Makefile
  Tiltfile
  api/v1alpha2/linodecluster_types.go
  clients/clients.go
  cloud/scope/cluster.go
  cloud/scope/common.go
  cloud/scope/common_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_bucket.go
  cloud/scope/object_storage_bucket_test.go
  cloud/scope/vpc.go
  cloud/services/domains.go
  cloud/services/domains_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/default/.gitignore
  config/default/linode-token-secret.yaml
  config/default/manager_credentials_patch.yaml
  config/manager/manager.yaml
  controller/linodecluster_controller.go
  controller/linodecluster_controller_test.go
  controller/linodemachine_controller.go
  controller/linodemachine_controller_test.go
  devbox.lock
  envrc.example
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  templates/addons/cluster-resource-set/secret.yaml
  templates/flavors/kubeadm/dns-loadbalancing/kustomization.yaml
  templates/infra/secret.yaml
  util/reconciler/defaults.go
Labels: new-feature

#379 [fix] set default value for dns token to be the linode api token
  config/default/linode-token-secret.yaml
  templates/infra/secret.yaml
Labels: bugfix
