Repository linode/cluster-api-provider-linode, pull requests merged in 2025-07, with the labels that each got.

#794 [ci] pass environment setting for e2e workflow
  .github/workflows/build_test_ci.yml
  .github/workflows/e2e-test.yaml
Labels: repo-ci-improvement

#790 [feat, breaking] add LMT controller to support tag propagation, remove tag propagation via annotations
  .gitignore
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodemachinetemplate_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/machine_template.go
  cloud/scope/machine_template_test.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  config/rbac/role.yaml
  docs/src/reference/out.md
  docs/src/topics/tag-propagation.md
  e2e/linodemachinetemplate-controller/lmt-tags/assert-capi-resources.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/assert-lm-creation.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/assert-lm-tags-addition.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/assert-lm-tags-removal.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/chainsaw-test.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/create-cluster.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/lmt-add-tags.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/lmt-remove-tags.yaml
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodemachinetemplate_controller.go
  internal/controller/linodemachinetemplate_controller_test.go
  util/helpers.go
Labels: new-feature, breaking-change

#789 [feat] Add VPC and Subnet retention and adoption
  api/v1alpha2/linodevpc_types.go
  clients/clients.go
  cmd/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  docs/src/reference/out.md
  docs/src/topics/vpc.md
  internal/controller/linodevpc_controller.go
  internal/controller/linodevpc_controller_helpers.go
  internal/controller/linodevpc_controller_test.go
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  util/errors.go
Labels: new-feature

#801 [CI] : allow all githubusercontent.com calls
  .github/workflows/build_test_ci.yml
  .github/workflows/go-analyze.yml
  .github/workflows/pull_request_ci.yaml
Labels: repo-ci-improvement

#773 [feat] : allocate ipv6 /64 cidrs to linodes
  api/v1alpha2/linodevpc_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  docs/src/reference/out.md
  go.mod
  go.sum
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodevpc_controller_helpers.go
  internal/controller/linodevpc_controller_test.go
  internal/webhook/v1alpha2/linodevpc_webhook.go
  internal/webhook/v1alpha2/linodevpc_webhook_test.go
Labels: new-feature

#806 [improvement] Add NetworkHelper field to LinodeMachineSpec and update instance configuration logic
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  docs/src/reference/out.md
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_test.go
  templates/flavors/kubeadm/flatcar/patch-flatcar.yaml
Labels: improvement

#807 [fix] Make ID the source of truth for vpc and subnet names
  internal/controller/linodevpc_controller_helpers.go
  internal/controller/linodevpc_controller_test.go
Labels: bugfix
