Repository linode/cluster-api-provider-linode, pull requests merged in 2025-03, with the labels that each got.

#681 [docs] : update readme, add info about management cluster
  README.md
  docs/src/topics/getting-started.md
Labels: documentation

#678 [feat] Nodebalancer VPC Integration
  api/v1alpha2/linodecluster_types.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  docs/src/reference/out.md
  go.mod
  go.sum
  internal/controller/linodecluster_controller_helpers.go
  internal/controller/linodecluster_controller_helpers_test.go
  util/helpers.go
  util/helpers_test.go
Labels: new-feature

#688 [deps] : bump ccm version to v0.4.25
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: dependencies

#679 [fix] Pause placement group when pausing linode machine
  .golangci.yml
  internal/controller/linodecluster_controller.go
  internal/controller/linodemachine_controller.go
Labels: bugfix

#690 [improvement] add info log for the api URL
  cmd/main.go
Labels: improvement

#696 [improvement] toggle cis hardening for rke2 clusters
  docs/src/topics/flavors/rke2.md
  templates/flavors/rke2/default/rke2ConfigTemplate.yaml
  templates/flavors/rke2/default/rke2ControlPlane.yaml
Labels: improvement

#702 [deps] : update CCM to v0.5.2
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: dependencies

#701 Update Makefile to bump CONVERSION_GEN_VERSION to v0.32.2
  Makefile
Labels: dependencies

#708 [feat] Adding ability to BYO VPC and configure with it
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  docs/src/reference/out.md
  docs/src/topics/firewalling.md
  docs/src/topics/vpc.md
  internal/controller/linodecluster_controller.go
  internal/controller/linodecluster_controller_test.go
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodemachine_controller_test.go
  internal/webhook/v1alpha2/linodecluster_webhook.go
  internal/webhook/v1alpha2/linodecluster_webhook_test.go
  internal/webhook/v1alpha2/linodemachine_webhook.go
  internal/webhook/v1alpha2/linodemachine_webhook_test.go
Labels: feature, new-feature

#709 Refactor reconciliation logic in Linode controllers to handle deletion cases gracefully
  internal/controller/linodefirewall_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodeplacementgroup_controller.go
  internal/controller/linodevpc_controller.go
Labels: bugfix

#711 Increase assert timeout for e2e test in GHA
  .github/workflows/build_test_ci.yml
  .github/workflows/e2e-upgrade-test.yaml
  Makefile
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
Labels: repo-ci-improvement

#710 Skip webhook validation during the move operation
  internal/webhook/v1alpha2/linodecluster_webhook.go
  internal/webhook/v1alpha2/linodecluster_webhook_test.go
  internal/webhook/v1alpha2/linodemachine_webhook.go
  internal/webhook/v1alpha2/linodemachine_webhook_test.go
  internal/webhook/v1alpha2/linodeplacementgroup_webhook.go
  internal/webhook/v1alpha2/linodeplacementgroup_webhook_test.go
  internal/webhook/v1alpha2/linodevpc_webhook.go
  internal/webhook/v1alpha2/linodevpc_webhook_test.go
  internal/webhook/v1alpha2/webhook_helpers.go
  internal/webhook/v1alpha2/webhook_suite_test.go
Labels: bugfix
