Repository linode/cluster-api-provider-linode, pull requests merged in 2025-09, with the labels that each got.

#860 [improvement] Increase RLIMIT_MEMLOCK in containers
  scripts/pre-kubeadminit.sh
Labels: improvement

#859 [improvement] Remove v1beta2 conditions package
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodemachinetemplate_types.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/linodeplacementgroup_types.go
  api/v1alpha2/linodevpc_types.go
  internal/controller/linodecluster_controller.go
  internal/controller/linodecluster_controller_test.go
  internal/controller/linodefirewall_controller.go
  internal/controller/linodefirewall_controller_test.go
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodemachinetemplate_controller.go
  internal/controller/linodeobjectstoragebucket_controller.go
  internal/controller/linodeobjectstoragebucket_controller_test.go
  internal/controller/linodeobjectstoragekey_controller.go
  internal/controller/linodeobjectstoragekey_controller_test.go
  internal/controller/linodeplacementgroup_controller.go
  internal/controller/linodevpc_controller.go
  internal/controller/linodevpc_controller_test.go
  internal/controller/suite_test.go
  util/reconciler/conditions.go
Labels: cleanup, improvement

#862 [improvement] enable SSA tag linter
  .golangci-kal.yml
  api/v1alpha2/firewallrule_types.go
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodemachinetemplate_types.go
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/linodevpc_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_firewallrules.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
Labels: improvement

#871 [improvement] shorten resource names for templates and tests for easier compatibility with Linode API label length limits
  docs/src/topics/disks/data-disks.md
  docs/src/topics/vpc.md
  e2e/admission-webhooks/validating/chainsaw-test.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
  e2e/linodecluster-controller/firewall-integration/chainsaw-test.yaml
  e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
  e2e/linodefirewall-controller/linodefirewall-addressset/chainsaw-test.yaml
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/chainsaw-test.yaml
  e2e/linodefirewall-controller/minimal-linodefirewall/chainsaw-test.yaml
  e2e/linodemachine-controller/cluster-object-store/chainsaw-test.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/chainsaw-test.yaml
  e2e/linodeobjectstoragebucket-controller/force-delete-linodeobjectstoragebucket/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/custom-secret/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/deprecated-secret/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/chainsaw-test.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/chainsaw-test.yaml
  e2e/linodevpc-controller/minimal-linodevpc/chainsaw-test.yaml
  templates/addons/machine-health-check/machinehealthcheck.yaml
  templates/flavors/clusterclass-kubeadm/clusterClass.yaml
  templates/flavors/clusterclass-kubeadm/deleteTransformer.yaml
  templates/flavors/clusterclass-kubeadm/kubeadmControlPlaneTemplate.yaml
  templates/flavors/clusterclass-kubeadm/kustomization.yaml
  templates/flavors/clusterclass-kubeadm/replacementTransformer.yaml
  templates/flavors/k3s/cluster-autoscaler/kustomization.yaml
  templates/flavors/k3s/default/k3sConfigTemplate.yaml
  templates/flavors/k3s/default/k3sControlPlane.yaml
  templates/flavors/k3s/dual-stack/kustomization.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/full/kustomization.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/kustomization.yaml
  templates/flavors/kubeadm/cluster-autoscaler/kustomization.yaml
  templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
  templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
  templates/flavors/kubeadm/dual-stack/kustomization.yaml
  templates/flavors/kubeadm/etcd-disk/kustomization.yaml
  templates/flavors/kubeadm/flatcar/patch-flatcar.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/full/kustomization.yaml
  templates/flavors/kubeadm/konnectivity/kustomization.yaml
  templates/flavors/kubeadm/self-healing/kustomization.yaml
  templates/flavors/rke2/cluster-autoscaler/kustomization.yaml
  templates/flavors/rke2/default/rke2ConfigTemplate.yaml
  templates/flavors/rke2/default/rke2ControlPlane.yaml
  templates/flavors/rke2/etcd-disk/kustomization.yaml
  templates/flavors/rke2/full-vpcless/kustomization.yaml
  templates/flavors/rke2/full/kustomization.yaml
  templates/infra/cluster.yaml
  templates/infra/linodeMachineTemplate.yaml
  templates/infra/machineDeployment.yaml
Labels: improvement

#880 [improvement] [breaking] make subnetID optional and align new interface field names with existing field names
  .golangci-kal.yml
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodevpc_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  docs/src/reference/out.md
  internal/controller/linodemachine_controller_helpers.go
Labels: improvement, breaking-change
