Repository linode/cluster-api-provider-linode, pull requests merged in 2025-06, with the labels that each got.

#758 [deps] bump CSI driver to v1.0.6
  templates/addons/csi-driver-linode/linode-csi.yaml
Labels: dependencies

#759 [deps] bump cilium to 1.17.4
  templates/addons/cilium/cilium.yaml
Labels: dependencies

#765 [deps] pin gh-release action version due to broken latest release
  .github/workflows/release.yml
Labels: dependencies

#771 [fix,deps]: Downgrade cilium to 1.16.10
  templates/addons/cilium/cilium.yaml
Labels: dependencies

#772 [feat] Propagate tags on LinodeMachine to Linodes
  clients/clients.go
  docs/src/topics/tag-propagation.md
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodemachine_controller_test.go
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
  util/helpers.go
Labels: new-feature

#776 [docs] fix doc title, add tag propagation to summary, sort pages alphabetically
  docs/src/SUMMARY.md
  docs/src/topics/tag-propagation.md
Labels: documentation

#777 [ci]: remove unnecessary dependent resource deletion
  Makefile
Labels: repo-ci-improvement

#781 [fix] continue to use .Spec.Tags until it is actually removed from the CRD
  internal/controller/linodemachine_controller_helpers.go
Labels: bugfix
