Repository linode/cluster-api-provider-linode, pull requests merged in 2025-02, with the labels that each got.

#658 [fix] Added jq devbox dependency and fixed missing /bin directory
  Makefile
  devbox.json
  devbox.lock
Labels: bugfix

#659 [docs] Add note about machine count variables
  docs/src/topics/getting-started.md
Labels: documentation

#649 [CI] : add flag to skip custom delete logic
  Makefile
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/check-child-cluster-vpc-and-firewall-deleted.yaml
Labels: repo-ci-improvement

#663 [feat] pause implementation for CAPL controllers
  internal/controller/linodecluster_controller.go
  internal/controller/linodecluster_controller_test.go
  internal/controller/linodefirewall_controller_test.go
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodeobjectstoragebucket_controller.go
  internal/controller/linodeobjectstoragebucket_controller_test.go
  internal/controller/linodeobjectstoragekey_controller.go
  internal/controller/linodeobjectstoragekey_controller_test.go
  internal/controller/linodevpc_controller_test.go
Labels: new-feature

#673 [deps] [CI] : bump ccm version
  .github/workflows/go-analyze.yml
  .golangci.yml
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: dependencies, repo-ci-improvement

#677 [improvement] Select subnet for cluster
  api/v1alpha2/linodecluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  docs/src/reference/out.md
  docs/src/topics/vpc.md
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_test.go
  templates/addons/ccm-linode/ccm-linode.yaml
  templates/addons/cilium/cilium.yaml
  templates/flavors/clusterclass-kubeadm/cluster-template.yaml
  templates/flavors/k3s/default/k3sControlPlane.yaml
  templates/infra/cluster.yaml
  templates/infra/linodeCluster.yaml
Labels: improvement
