Repository linode/cluster-api-provider-linode, pull requests merged in 2025-08, with the labels that each got.

#816 [improvement] : Update dualstack flavors
  docs/src/SUMMARY.md
  docs/src/topics/flavors/dual-stack.md
  docs/src/topics/flavors/nodeipam-ccm.md
  templates/flavors/k3s/dual-stack/kustomization.yaml
  templates/flavors/kubeadm/dual-stack/kustomization.yaml
  templates/flavors/kubeadm/nodeipam-ccm/kustomization.yaml
Labels: improvement

#813 [feat] make firewallID mutable, propagate it from lmt->lm
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodemachinetemplate_types.go
  clients/clients.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
  docs/src/reference/out.md
  e2e/linodemachine-controller/linodemachine-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  go.mod
  go.sum
  internal/controller/linodemachine_controller.go
  internal/controller/linodemachine_controller_test.go
  internal/controller/linodemachinetemplate_controller.go
  internal/controller/linodemachinetemplate_controller_test.go
  mock/client.go
  observability/wrappers/linodeclient/linodeclient.gen.go
Labels: new-feature

#803 [feat] Add Support for VPC only backends
  api/v1alpha2/linodecluster_types.go
  cloud/services/loadbalancers.go
  cloud/services/loadbalancers_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
  docs/src/reference/out.md
  hack/generate-flavors.sh
  internal/controller/linodecluster_controller_helpers.go
  internal/controller/linodecluster_controller_helpers_test.go
  internal/controller/linodecluster_controller_test.go
Labels: new-feature

#836 [feat] remove defaultLinodeClient used by webhooks in favor of always using an authenticated client
  internal/webhook/v1alpha2/linodecluster_webhook.go
  internal/webhook/v1alpha2/linodeclustertemplate_webhook.go
  internal/webhook/v1alpha2/linodemachine_webhook.go
  internal/webhook/v1alpha2/linodeobjectstoragebucket_webhook.go
  internal/webhook/v1alpha2/linodeobjectstoragebucket_webhook_test.go
  internal/webhook/v1alpha2/linodeplacementgroup_webhook.go
  internal/webhook/v1alpha2/linodevpc_webhook.go
  internal/webhook/v1alpha2/webhook_helpers.go
Labels: new-feature

#849 [ci] set the ref for e2e-test and pr-labeler
  .github/workflows/e2e-test.yaml
  .github/workflows/pr-labeler.yml
Labels: repo-ci-improvement

#842 [test][fix] E2E test improvements, add missing client for the LOBJ webhook
  .github/filters.yml
  Makefile
  e2e/admission-webhooks/validating/chainsaw-test.yaml
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
  e2e/linodecluster-controller/firewall-integration/chainsaw-test.yaml
  e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
  e2e/linodefirewall-controller/linodefirewall-addressset/chainsaw-test.yaml
  e2e/linodefirewall-controller/linodefirewall-firewall-rule/chainsaw-test.yaml
  e2e/linodefirewall-controller/minimal-linodefirewall/chainsaw-test.yaml
  e2e/linodemachine-controller/cluster-object-store/chainsaw-test.yaml
  e2e/linodemachine-controller/linodecluster-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/linodemachine-vpcref-integration/chainsaw-test.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/chainsaw-test.yaml
  e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
  e2e/linodemachinetemplate-controller/lmt-tags/chainsaw-test.yaml
  e2e/linodeobjectstoragebucket-controller/force-delete-linodeobjectstoragebucket/chainsaw-test.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-capi-resources.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/assert-obj.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/check-obj-deletion.yaml
  e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/create-linodeobjectstoragebucket.yaml
  e2e/linodeobjectstoragekey-controller/custom-secret/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/deprecated-secret/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/chainsaw-test.yaml
  e2e/linodeplacementgroup-controller/minimal-linodeplacementgroup/chainsaw-test.yaml
  e2e/linodevpc-controller/minimal-linodevpc/chainsaw-test.yaml
  internal/webhook/v1alpha2/linodeobjectstoragebucket_webhook.go
Labels: testing, bugfix

#850 [deps] Update linodego to v1.56.0
  config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
  go.mod
  go.sum
  internal/controller/linodemachine_controller_helpers.go
  internal/controller/linodemachine_controller_test.go
Labels: dependencies

#841 [improvement] enable the `optionalorrequired` linter for the various APIs
  .golangci-kal.yml
  api/v1alpha2/addressset_types.go
  api/v1alpha2/firewallrule_types.go
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodeclustertemplate_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodemachinetemplate_types.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/linodeplacementgroup_types.go
  api/v1alpha2/linodevpc_types.go
Labels: improvement
