Repository linode/cluster-api-provider-linode, pull requests merged in 2025-05, with the labels that each got.

#741 [improvement] Change LinodePlacementGroup Deletion Logic to requeue when nodes are attached
  internal/controller/linodeplacementgroup_controller.go
  internal/controller/linodeplacementgroup_controller_test.go
  util/reconciler/defaults.go
Labels: improvement

#747 [improvement] Add AWS dependency patterns to Dependabot configuration
  .github/dependabot.yml
Labels: improvement

#746 [improvement] Implement owner refs for linode resources
  Makefile
  cmd/main.go
  docs/src/SUMMARY.md
  docs/src/topics/resource-ownership.md
  internal/controller/linodefirewall_controller.go
  internal/controller/linodeobjectstoragebucket_controller.go
  internal/controller/linodeobjectstoragekey_controller.go
  internal/controller/linodeplacementgroup_controller.go
  internal/controller/linodevpc_controller.go
  util/helpers.go
  util/helpers_test.go
Labels: improvement

#749 [fix] Remove deletion of LinodeVPC and LinodeFirewall in e2etest
  e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
  e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
Labels: bugfix

#750 [breaking] Simplify field names for OBJ bucket, fix broken flatcar link in docs
  cloud/scope/common.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/object_storage_key.go
  cloud/scope/object_storage_key_test.go
  cloud/services/object_storage_objects_test.go
  docs/src/topics/backups.md
  docs/src/topics/cluster-object-store.md
  docs/src/topics/flavors/flatcar.md
  e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
  e2e/linodemachine-controller/cluster-object-store/assert-key-and-secret.yaml
  e2e/linodemachine-controller/cluster-object-store/create-linodeobjectstoragekey.yaml
  e2e/linodeobjectstoragekey-controller/custom-secret/assert-key-and-secret.yaml
  e2e/linodeobjectstoragekey-controller/custom-secret/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/custom-secret/check-key-and-secret-deletion.yaml
  e2e/linodeobjectstoragekey-controller/custom-secret/create-linodeobjectstoragekey.yaml
  e2e/linodeobjectstoragekey-controller/deprecated-secret/assert-key-and-secret.yaml
  e2e/linodeobjectstoragekey-controller/deprecated-secret/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/deprecated-secret/check-key-and-secret-deletion.yaml
  e2e/linodeobjectstoragekey-controller/deprecated-secret/create-linodeobjectstoragekey.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/assert-key-and-secret.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/chainsaw-test.yaml
  e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/check-key-and-secret-deletion.yaml
  internal/controller/linodemachine_controller_helpers_test.go
  internal/controller/linodeobjectstoragekey_controller_test.go
  templates/addons/cluster-object-store/cluster-object-store.yaml
  templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
  templates/addons/etcd-backup-restore/linode-obj.yaml
Labels: breaking-change
