Repository linode/cluster-api-provider-linode, pull requests merged in 2025-01, with the labels that each got.

#615 [deps] : update ccm version
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: dependencies

#616 [docs] FIx README badge links
  README.md
Labels: documentation

#617 [fix] remove unused crd
  api/v1alpha2/addressset_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_addressset.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_addresssets.yaml
Labels: bugfix

#614 [improvement] : allow CCM to work with different environments in CAPL
  templates/addons/ccm-linode/ccm-linode.yaml
  templates/addons/cluster-resource-set/secret.yaml
  templates/flavors/k3s/default/kustomization.yaml
  templates/flavors/k3s/full-vpcless/kustomization.yaml
  templates/flavors/k3s/vpcless/kustomization.yaml
  templates/flavors/kubeadm/cilium-bgp-lb/kustomization.yaml
  templates/flavors/kubeadm/full-vpcless/kustomization.yaml
  templates/flavors/kubeadm/vpcless/kustomization.yaml
  templates/flavors/rke2/default/kustomization.yaml
  templates/flavors/rke2/vlan/kustomization.yaml
  templates/flavors/rke2/vpcless/kustomization.yaml
Labels: improvement

#619 [fix] Delete bootstrap data from object store only if provided
  internal/controller/linodemachine_controller_helpers.go
Labels: bugfix

#625 [improvement] : allow csi driver to run in different environments
  templates/addons/csi-driver-linode/linode-csi.yaml
Labels: improvement

#618 [docs] : add doc for CCM
  docs/src/SUMMARY.md
  docs/src/topics/linode-cloud-controller-manager.md
Labels: documentation

#626 [improvement] : remove LINODE_CA and use LINODE_CA_BASE64 only
  Tiltfile
  docs/src/developers/development.md
  docs/src/topics/linode-cloud-controller-manager.md
Labels: improvement

#628 [fix] : set reason to none if nothing specified
  api/v1alpha2/linodecluster_types.go
  api/v1alpha2/linodefirewall_types.go
  api/v1alpha2/linodemachine_types.go
  api/v1alpha2/linodeobjectstoragebucket_types.go
  api/v1alpha2/linodeobjectstoragekey_types.go
  api/v1alpha2/linodeplacementgroup_types.go
  api/v1alpha2/linodevpc_types.go
Labels: bugfix

#627 [docs] update token permissions in getting started
  docs/src/topics/getting-started.md
Labels: documentation

#630 [fix] : use UseURL to correctly parse URLs
  cloud/scope/common.go
Labels: bugfix

#636 [CI] : add workflow to test upgrade
  .github/workflows/e2e-upgrade-test.yaml
  Makefile
  e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
Labels: repo-ci-improvement

#638 [CI] : update GHA branch to correct branch
  .github/workflows/e2e-upgrade-test.yaml
Labels: repo-ci-improvement

#641 [fix] fix cni plugins version - the release 1.6.1 is broken on github
  scripts/pre-kubeadminit.sh
Labels: bugfix

#640 [improvement] add support for custom CAPL CAs in kustomize
  Tiltfile
  config/default/capl-ca.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
Labels: improvement

#639 [fix] Add to dns only if machines are ready + Fix AWS sdk behavior
  cloud/scope/common.go
  cloud/services/domains.go
Labels: bugfix

#642 [CI] : increase assert timeout from 5m to 10m
  .chainsaw.yaml
Labels: repo-ci-improvement

#652 [deps] : update ccm to v0.4.23
  templates/addons/ccm-linode/ccm-linode.yaml
Labels: dependencies

#651 chore: enable metadata gzip compression
  config/manager/manager.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/assert-capi-resources.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/assert-linodemachine.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/chainsaw-test.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/check-linodemachine-deletion.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/create-cluster.yaml
  e2e/linodemachine-controller/metadata-gzip-compression/create-linodemachine.yaml
Labels: testing

#650 [test] e2e: linodemachine: cluster object store
  e2e/linodemachine-controller/cluster-object-store/assert-capi-resources.yaml
  e2e/linodemachine-controller/cluster-object-store/assert-key-and-secret.yaml
  e2e/linodemachine-controller/cluster-object-store/assert-linodemachine.yaml
  e2e/linodemachine-controller/cluster-object-store/chainsaw-test.yaml
  e2e/linodemachine-controller/cluster-object-store/check-linodemachine-deletion.yaml
  e2e/linodemachine-controller/cluster-object-store/create-cluster.yaml
  e2e/linodemachine-controller/cluster-object-store/create-linodemachine.yaml
  e2e/linodemachine-controller/cluster-object-store/create-linodeobjectstoragekey.yaml
Labels: testing
